server:
  port: 8080
  error:
    include-binding-errors: always
    include-message: always
spring:
  application:
    name: gateway
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
      loadbalancer:
        mode: service
    gateway:
      routes:
        - id: batch-service
          predicates:
            - Path=/batch/**
          filters:
            - StripPrefix=1
          uri: lb://batch-service
        - id: employee-service
          predicates:
            - Path=/employee/**
          filters:
            - StripPrefix=1
          uri: lb://employee-service
        - id: login-service
          predicates:
            - Path=/login/**
          filters:
            - StripPrefix=1
          uri: lb://login-service
        - id: salary-service
          predicates:
            - Path=/salary/**
          filters:
            - StripPrefix=1
          uri: lb://salary-service
        - id: total-service
          predicates:
            - Path=/total/**
          filters:
            - StripPrefix=1
          uri: lb://total-service
      default-filters:
        - name: JwtGlobalFilter
          args:
            baseMessage: gateway filter
            preLogger: true
            postLogger: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://www.songboseok.shop","https://www.songboseok.shop"
            allow-credentials: true
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
jwt:
  secretKey: ${JWT_SECRETKEY}
