apiVersion: apps/v1
kind: Deployment
metadata:
  name: batch-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: batch
  template:
    metadata:
      labels:
        app: batch
    spec:
      containers:
        - name: batch-backend
          image: 533267394261.dkr.ecr.ap-northeast-2.amazonaws.com/harbor-batch:latest
          ports:
            - containerPort: 8005

          resources:
            limits:
              cpu: "1"
              memory: "500Mi"
            requests:
              cpu: "0.5"
              memory: "250Mi"
          ##### Kubectl secrets #####
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-infos
                  key: DB_HOST
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-infos
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-infos
                  key: DB_PASSWORD
            - name: JWT_SECRETKEY
              valueFrom:
                secretKeyRef:
                  name: db-infos
                  key: JWT_SECRETKEY
            - name: HOST
              valueFrom:
                secretKeyRef:
                  name: db-infos
                  key: HOST
---
apiVersion: v1
kind: Service
metadata:
  name: batch-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8005
  selector:
    app: batch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fabric8-rbac
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default # pod의 네임스페이스
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io